workflows:
  android-build:
    name: Build APK
    environment:
      flutter: stable
      vars:
        FLUTTER_ROOT: /Users/builder/programs/flutter
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
