name: messenger_app
description: Orbitgram messenger
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  confetti: ^0.7.0   # для анимации премиума

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true